### PR TITLE
Update to_feather path

### PR DESCRIPTION
**Pull request by johnflavin**
`to_feather` is currently typed to only accept a `str` for its `path`, but upstream it was updated to accept `FilePathOrBuffer[AnyStr]`. See pandas-dev/pandas#35408.

### CODE REVIEW

**Review by zkrolikowski-vl — APPROVED** [review]

**Comment by zkrolikowski-vl** [comment]
Great job catching this @johnflavin. You can go ahead and merge.

**Review by joannasendorek — APPROVED** [review]

**Comment by johnflavin** [comment]
> Great job catching this @johnflavin. You can go ahead and merge.

Thanks! I would merge, but I don’t have permission. Someone with write access will need to click the button.

**Comment by zkrolikowski-vl** [comment]
Ok. That's seems like double-approval. Something to configure I guess. The master changes is just a logo, so I'll go ahead and merge.

**Comment by zkrolikowski-vl** [comment]
Thanks for contributing @johnflavin !

**Pull request merged**
