### PR TITLE
Make annotation for `.copy()` more precise

### PR DESCRIPTION
**Pull request by aneeshusa**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.copy.html
says the return value's `Object type matches caller.`

Previously, this returned a `FrameOrSeries` which was less ergonomic.
Without this fix, the newly added tests fail:

```
(venv3) aagrawal@aagrawal-mbp151 ~/src/pandas-stubs $ mypy --config-file mypy.ini third_party/3/pandas tests/snippets
tests/snippets/test_series.py:40: error: Incompatible types in assignment (expression has type "Union[DataFrame, Series]", variable has type "Series")
tests/snippets/test_frame.py:47: error: Incompatible types in assignment (expression has type "Union[DataFrame, Series]", variable has type "DataFrame")
Found 2 errors in 2 files (checked 241 source files)
```

### CODE REVIEW

**Comment by aneeshusa** [comment]
Please let me know if I should bump the version in setup.py. I didn't see a changelog to update.
I'm new to pandas and found pandas-stubs a few days ago - it's been really helpful! Would also love to see https://github.com/VirtusLab/pandas-stubs/pull/33 make progress as I'm using the `na_action` to `DataFrame.applymap`.

**Comment by zkrolikowski-vl** [comment]
Hi @aneeshusa. Great change!

If you could just bump the version to `1.1.0.7` then we can merge.

**Comment by aneeshusa** [comment]
@zkrolikowski-vl thanks for the review, pushed a change to bump the version.
Do you need to do anything to make CI run? Want to make sure it's working not just on my machine!

**Comment by zkrolikowski-vl** [comment]
There seems to be an issue and CI didn't trigger for a forked PR. Let me merge this and CI will run on master before a release.

**Review by zkrolikowski-vl — APPROVED** [review]

**Pull request merged**
